config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  resources :articles
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :move_to_index, except: [:index, :show]
	before_action :set_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.includes(:user).order("created_at DESC")
	end

	def new
		@article = Article.new
	end

	def create
		Article.create(title: article_params[:title], text: article_params[:text], user_id: current_user.id)
		redirect_to action: :index
	end

	def edit
	end

	def update
		@article.update(article_params) if @article.user_id == current_user.id
		redirect_to action: :index
	end

	def destroy
		@article.destroy if @article.user_id == current_user.id
		redirect_to action: :index
	end

	def show
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

	def move_to_index
		redirect_to action: :index unless user_signed_in?
	end

	def set_article
		@article = Article.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		user = User.find(params[:id])
		@nickname = user.nickname
		@articles = user.articles
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div class="row valign-wrapper">
	<div class="col s8 offset-s2 valign">
		<div class="card grey lighten-5">
			<%# <div class="card-content white-text"> %>
			<div class="card-content">
				<span class="card-title"><%= article.title %></span>
				<%= simple_format(article.text, class: "truncate") %>
			</div>
			<div class="card-action">
				<%= link_to 'SHOW', article_path(article) %>
				<% if user_signed_in? && article.user_id == current_user.id %>
					<%= link_to 'EDIT', edit_article_path(article) %>
					<%= link_to 'DELETE', article_path(article), method: :delete %>
				<% end %>
				<%= link_to "Posted by #{article.user.nickname}", user_path(article.user_id), class: "posted-user" %>
			</div>
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<div class="row">
	<%= form_with model: @article, class: "col s12" do %>
		<div class="row">
			<div class="input-field col s6 offset-s2">
				<%= text_field(:article, :title, class: "validate") %>
				<%= label_tag "title", "Title", class: "active" %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s8 offset-s2">
				<%= text_area(:article, :text, class: "materialize-textarea") %>
				<%= label_tag "text", "Text", class: "active" %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s8 offset-s2">
				<%= button_tag type: "submit", class: "waves-effect waves-light btn" do %>
				SUBMIT<i class="material-icons right">send</i>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<%= render partial: "article", locals: {article: article} %>
<% end %>

app/views/articles/new.html.erb
<div class="row">
	<%= form_with model: @article, class: "col s12" do %>
		<div class="row">
			<div class="input-field col s6 offset-s2">
				<%= text_field(:article, :title, class: "validate") %>
				<%= label_tag "title", "Title" %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s8 offset-s2">
				<%= text_area(:article, :text, class: "materialize-textarea") %>
				<%= label_tag "text", "Text" %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s8 offset-s2">
				<%= button_tag type: "submit", class: "waves-effect waves-light btn" do %>
				SUBMIT<i class="material-icons right">send</i>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="row valign-wrapper">
	<div class="col s8 offset-s2 valign">
		<div class="card grey lighten-5">
			<div class="card-content">
				<span class="card-title"><%= @article.title %></span>
				<%= simple_format(@article.text) %>
			</div>
				<div class="card-action">
				<% if user_signed_in? && @article.user_id == current_user.id %>
					<%= link_to 'EDIT', edit_article_path(@article) %>
					<%= link_to 'DELETE', article_path(@article), method: :delete %>
				<% end %>
				<%= link_to '', '', class: "dummy" %>
				<%= link_to "Posted by #{@article.user.nickname}", user_path(@article.user_id), class: "posted-user" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <nav class="cyan darken-3">
        <div class="nav-wrapper">
          <%= link_to 'Mini Blog', articles_path, class: 'brand-logo center' %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: 'waves-effect waves-light btn' do %>
                  <i class="material-icons left mypage-mark">home</i><span>MYPAGE</span>
                <% end %>
              </li>
              <li><%= link_to 'NewPost', new_article_path, class: 'waves-effect waves-light btn' %></li>
              <li><%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: 'waves-effect waves-light btn' %></li>
            <% else %>
              <li><%= link_to 'LogIn', new_user_session_path, class: 'waves-effect waves-light btn' %></li>
              <li><%= link_to 'SignUp', new_user_registration_path, class: 'waves-effect waves-light btn' %></li>
            <% end %>
          </ul>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <% if user_signed_in? %>
              <li><i class="material-icons left login-mark">person</i><span>USER : <%= current_user.nickname %></span></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div class="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h4 class="center-align contents-title">Articles posted by <%= @nickname %></h4>

<% @articles.each do |article| %>
	<%= render partial: "articles/article", locals: {article: article} %>
<% end %>